name: Auto News System

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kütüphaneleri yükle
        run: |
          pip install feedparser

      - name: Haber sistemi çalıştır
        run: |
          python news_generator.py

      - name: Commit at
        run: |
          git config --global user.name "News Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Otomatik haber güncellemesi" || echo "Değişiklik yok"
          git push
